import { Logo } from "@/components/Logo";

export const metadata = {
  title: "Terms & Conditions — Threadly",
};

export default function TermsPage() {
  return (
    <>
      <header className="legal-header">
        <a href="/" className="legal-header-inner">
          <Logo size={22} />
          Threadly
        </a>
      </header>

      <article className="legal">
        <h1>Terms &amp; Conditions</h1>
        <p className="updated">Last updated: August 7, 2026</p>

        <p>
          These Terms &amp; Conditions (&quot;Terms&quot;) govern your access to and use of
          Threadly (&quot;Threadly,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) and
          the Threadly website and application (the &quot;Service&quot;). By creating an account
          or otherwise using the Service, you agree to be bound by these Terms. If you do not
          agree, do not use the Service.
        </p>

        <h2>1. What Threadly does</h2>
        <p>
          Threadly is an AI-assisted social monitoring and reply-drafting tool. It connects to
          social platforms you authorize (X/Twitter), searches for conversations
          matching criteria you configure, and drafts a suggested reply using AI. It never
          publishes, posts, or sends anything on your behalf automatically —{" "}
          <strong>every draft requires your explicit approval before it is published</strong>.
          This is a permanent feature of the Service, not something available only in an early
          version, and it will not be removed or made optional to bypass.
        </p>

        <h2>2. Eligibility</h2>
        <p>
          You must be at least 18 years old and capable of forming a binding contract to use the
          Service. If you use the Service on behalf of a business or organization, you represent
          that you are authorized to bind that entity to these Terms.
        </p>

        <h2>3. Your account</h2>
        <p>
          You are responsible for maintaining the confidentiality of your password and for all
          activity that occurs under your account. Notify us immediately of any unauthorized use
          of your account.
        </p>

        <h2>4. Subscription, free trial, and billing</h2>
        <ul>
          <li>New accounts start with a 7-day free trial. A valid payment card is required to start the trial.</li>
          <li>Unless canceled before the trial ends, your card will be automatically charged the then-current subscription price (currently $49/month) at the end of the trial, and monthly thereafter until you cancel.</li>
          <li>You can cancel anytime from your dashboard&apos;s billing page, which is self-service and takes effect at the end of your current billing period. We do not provide prorated refunds for partial billing periods.</li>
          <li>All payments are processed by Polar, acting as merchant of record. Your relationship for payment purposes is with Polar; Threadly does not handle or store your card details.</li>
          <li>We may change our pricing with at least 30 days&apos; notice to active subscribers; continued use after a price change takes effect constitutes acceptance of the new price.</li>
        </ul>

        <h2>5. Connecting third-party platforms</h2>
        <p>
          When you connect X/Twitter, you authorize Threadly to access that
          account via the OAuth scopes granted during that platform&apos;s own consent flow, and
          to draft and, upon your approval, publish content through that connection. You are
          solely responsible for ensuring your use of Threadly, and any content approved and
          published through it, complies with that platform&apos;s own Terms of Service and
          policies. Threadly is not affiliated with, endorsed by, or responsible for X/Twitter
          or any other third-party platform, and we are not responsible for
          their availability, API changes, rate limits, or account actions they take (including
          suspension) as a result of activity on your connected account. You can disconnect any
          platform at any time.
        </p>

        <h2>6. AI-generated content</h2>
        <p>
          Drafts are generated by AI and may be inaccurate, out of context, or unsuitable for
          publication. Threadly does not review drafts for accuracy before presenting them to
          you. You are solely responsible for reviewing and editing every draft before approving
          it, and you bear full responsibility for any content you choose to approve and publish
          — approving a draft is your own act of publication, not ours.
        </p>

        <h2>7. Acceptable use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Post spam, unsolicited advertising, or content that violates a connected platform&apos;s policies.</li>
          <li>Harass, threaten, defame, or impersonate any person.</li>
          <li>Attempt to circumvent the approval requirement described in Section 1, or use the Service in a way designed to auto-approve or bulk-approve content without genuine human review.</li>
          <li>Interfere with or disrupt the Service&apos;s infrastructure, or attempt to access accounts or data that aren&apos;t yours.</li>
          <li>Use the Service for any unlawful purpose.</li>
        </ul>
        <p>We may suspend or terminate accounts that violate this section.</p>

        <h2>8. Intellectual property</h2>
        <p>
          You retain all rights to the content you create, approve, or publish through Threadly.
          We retain all rights to the Threadly software, website, and branding. You&apos;re
          granted a limited, non-exclusive, non-transferable license to use the Service for your
          own business purposes during an active subscription.
        </p>

        <h2>9. Termination</h2>
        <p>
          You may stop using the Service and cancel your subscription at any time. We may
          suspend or terminate your access if you breach these Terms, fail to pay applicable
          fees, or if we discontinue the Service. Upon termination, your right to use the
          Service ends immediately; Sections 6, 8, 10, and 11 survive termination.
        </p>

        <h2>10. Disclaimers</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available,&quot; without
          warranties of any kind, express or implied, including merchantability, fitness for a
          particular purpose, and non-infringement. We do not warrant that the Service will be
          uninterrupted, error-free, or that AI-drafted content will be accurate, appropriate, or
          effective for your purposes.
        </p>

        <h2>11. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, Threadly and its operators will not be liable
          for any indirect, incidental, special, consequential, or punitive damages, or any loss
          of profits, revenue, data, or goodwill, arising from your use of the Service —
          including damages resulting from content you approved and published. Our total
          liability for any claim arising from these Terms or the Service will not exceed the
          amount you paid us in the 3 months preceding the claim.
        </p>

        <h2>12. Indemnification</h2>
        <p>
          You agree to indemnify and hold Threadly harmless from any claims, damages, or expenses
          arising from your use of the Service, your violation of these Terms, or content you
          approved and published through a connected platform.
        </p>

        <h2>13. Changes to these Terms</h2>
        <p>
          We may update these Terms from time to time. If we make material changes, we&apos;ll
          notify you by email or through the Service before the change takes effect. Continued
          use of the Service after changes take effect constitutes acceptance of the updated
          Terms.
        </p>

        <h2>14. Governing law</h2>
        <p>
          These Terms are governed by the laws of India, without regard to conflict-of-law
          principles. Any dispute arising from these Terms or the Service will be subject to the
          exclusive jurisdiction of the courts of India.
        </p>

        <h2>15. Contact us</h2>
        <p>
          Questions about these Terms can be sent to{" "}
          <a href="mailto:thumbflip.contact@gmail.com">thumbflip.contact@gmail.com</a>.
        </p>
      </article>
    </>
  );
}
