#!/usr/bin/env python3
"""Scaffolds a new plugin package — see docs/plugins/QUICKSTART.md and
docs/plugins/PLUGIN_ARCHITECTURE.md. Generates `plugins/<name>/` with a manifest, a
Protocol-honoring `plugin.py` stub (every method raises `NotImplementedError` — this
generates structure, not behavior), a `pyproject.toml` with the entry-point + the
package-dir packaging trick already correct, a `README.md`, and a `tests/` folder wired to
the shared contract suite.

This exists because docs/reviews/PLATFORM_READINESS_REVIEW.md found the setuptools
`package-dir` incantation required for a plugin's entry point to register is obscure,
undocumented tribal knowledge with no scaffolding to generate it — this script is that
scaffolding.

Run: python scripts/new_plugin.py <name> [--capabilities searchable,publishable]
                                          [--auth-type api_key|oauth2|session_credentials]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import TypedDict

REPO_ROOT = Path(__file__).resolve().parent.parent

VALID_CAPABILITIES = {"searchable", "publishable", "webhook_receivable", "metrics_queryable"}
VALID_AUTH_TYPES = {"oauth2", "api_key", "session_credentials"}


class _CapabilitySpec(TypedDict, total=False):
    protocol: str
    base_imports: list[str]
    events_imports: list[str]
    method: str


# capability -> (Protocol class name, extra names it needs imported from plugins._shared.base
# or plugins._shared.events, the stub method body)
_CAPABILITY_SPECS: dict[str, _CapabilitySpec] = {
    "searchable": {
        "protocol": "Searchable",
        "base_imports": ["PluginQuery", "PluginResult"],
        "method": (
            "async def search(self, query: PluginQuery) -> list[PluginResult]:\n"
            "        raise NotImplementedError"
        ),
    },
    "publishable": {
        "protocol": "Publishable",
        "base_imports": ["PublishResult"],
        "method": (
            "async def publish(self, item: object) -> PublishResult:\n"
            "        raise NotImplementedError"
        ),
    },
    "webhook_receivable": {
        "protocol": "WebhookReceivable",
        "base_imports": [],
        "events_imports": ["DomainEventPublisher"],
        "method": (
            "async def handle_webhook(\n"
            "        self, payload: dict, *, events: DomainEventPublisher\n"
            "    ) -> None:\n"
            "        raise NotImplementedError"
        ),
    },
    "metrics_queryable": {
        "protocol": "MetricsQueryable",
        "base_imports": ["MetricsQuerySpec", "MetricsResult"],
        "method": (
            "async def query_metrics(self, spec: MetricsQuerySpec) -> MetricsResult:\n"
            "        raise NotImplementedError"
        ),
    },
}


def _class_prefix(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _validate_name(name: str) -> None:
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        raise SystemExit(
            f"Plugin name must be lowercase snake_case (e.g. 'reddit', 'google_analytics'), "
            f"got {name!r}."
        )


def _write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def _manifest_py(name: str, capabilities: list[str], auth_type: str) -> str:
    prefix = _class_prefix(name)
    caps = ", ".join(f'"{c}"' for c in capabilities)

    # See docs/auth/OAUTH2_ARCHITECTURE.md ("Plugin SDK additions") — an oauth2 manifest
    # needs an OAuthProviderSpec; both the shared contract suite and plugin_catalog.py's
    # discovery step reject one without it. URLs/scopes are TODOs — this scaffold cannot
    # know the real provider's endpoints.
    import_lines = ["from plugins._shared.manifest import PluginManifest"]
    oauth_field = ""
    if auth_type == "oauth2":
        # "manifest" < "oauth" alphabetically — matches ruff's isort expectations.
        import_lines.append("from plugins._shared.oauth import OAuthProviderSpec")
        oauth_field = (
            "\n    oauth=OAuthProviderSpec(\n"
            '        authorize_url="TODO: https://provider.example/oauth/authorize",\n'
            '        token_url="TODO: https://provider.example/oauth/token",\n'
            "        scopes=(),  # TODO: this provider's required scopes\n"
            "    ),"
        )
    import_block = "\n".join(import_lines)

    return f'''"""See docs/plugins/PLUGIN_ARCHITECTURE.md. Generated by scripts/new_plugin.py —
fill in {prefix}ConnectionConfig's real fields and content_types, then delete this comment."""

from __future__ import annotations

from pydantic import BaseModel

{import_block}


class {prefix}ConnectionConfig(BaseModel):
    """Whatever a project needs to configure to connect this plugin (a subreddit allowlist,
    monitored channel IDs, ...). An empty model is valid if there's nothing to configure."""


MANIFEST = PluginManifest(
    key="{name}",
    interface_version="1.0",
    capabilities=({caps},),
    config_schema={prefix}ConnectionConfig,
    auth_type="{auth_type}",{oauth_field}
)
'''


def _import_line(module: str, names: list[str]) -> str:
    """A `from module import a, b, c` on one line, or ruff's preferred parenthesized
    multi-line form if that line would exceed the 100-char limit (tool.ruff.line-length in
    backend/pyproject.toml)."""
    single_line = f"from {module} import {', '.join(names)}"
    if len(single_line) <= 100:
        return single_line
    body = "".join(f"    {n},\n" for n in names)
    return f"from {module} import (\n{body})"


def _plugin_py(name: str, capabilities: list[str]) -> str:
    class_name = f"{_class_prefix(name)}Plugin"
    # Only the dataclasses each stub method's signature actually references are imported —
    # the Protocol names themselves (Searchable, Publishable, ...) are never referenced in
    # plugin.py: a plugin satisfies a Protocol structurally, by having the right methods, not
    # by importing or inheriting it. Importing them here would be an unused-import lint error.
    base_imports = sorted(
        {"ResolvedConnection", *(n for c in capabilities for n in _CAPABILITY_SPECS[c].get("base_imports", []))}
    )
    events_imports = sorted(
        {n for c in capabilities for n in _CAPABILITY_SPECS[c].get("events_imports", [])}
    )
    methods = "\n\n    ".join(str(_CAPABILITY_SPECS[c]["method"]) for c in capabilities)

    import_lines = [f"from plugins.{name}.manifest import MANIFEST"]
    import_lines.insert(0, _import_line("plugins._shared.base", base_imports))
    if events_imports:
        import_lines.insert(1, _import_line("plugins._shared.events", events_imports))

    return f'''"""See docs/plugins/PLUGIN_ARCHITECTURE.md. Generated by scripts/new_plugin.py —
every method below raises NotImplementedError; replace each with real behavior against the
actual external API, then delete this comment."""

from __future__ import annotations

{chr(10).join(import_lines)}


class {class_name}:
    manifest = MANIFEST

    def __init__(self, connection: ResolvedConnection) -> None:
        self._connection = connection

    {methods}

    async def health_check(self) -> bool:
        raise NotImplementedError


def create_plugin(connection: ResolvedConnection) -> {class_name}:
    return {class_name}(connection)
'''


def _pyproject_toml(name: str) -> str:
    return f'''[project]
name = "growthos-plugin-{name.replace("_", "-")}"
version = "0.0.1"
description = "GrowthOS plugin: {name}"
requires-python = ">=3.12"
dependencies = ["pydantic>=2.9"]

[project.entry-points."growthos.plugins"]
{name} = "plugins.{name}.manifest:MANIFEST"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["plugins.{name}"]
package-dir = {{"plugins.{name}" = "."}}
'''


def _readme_md(name: str, capabilities: list[str], auth_type: str) -> str:
    caps = ", ".join(f"`{c}`" for c in capabilities)
    return f'''# Plugin: {name}

**Capabilities:** {caps}
**Auth:** {auth_type}
**Status:** scaffolded by `scripts/new_plugin.py` — not yet implemented.

## Purpose

<what external system this plugin integrates with, and why a project would connect it>

## Setup

1. Fill in `manifest.py`'s `{_class_prefix(name)}ConnectionConfig` and `content_types`.
2. Implement each method in `plugin.py` (currently all raise `NotImplementedError`).
3. Install editable and run this plugin's own tests — see docs/plugins/QUICKSTART.md:

   ```
   uv pip install -e plugins/{name} --python backend/.venv   (run from repo root)
   backend/.venv/Scripts/python -m pytest plugins/{name}/tests -p no:cov   (Windows)
   backend/.venv/bin/python -m pytest plugins/{name}/tests -p no:cov       (macOS/Linux)
   ```
'''


def _test_contract_py(name: str, auth_type: str) -> str:
    prefix = _class_prefix(name)
    stdlib_imports = ["import uuid"]
    if auth_type == "oauth2":
        credentials_import = "from plugins._shared.credentials import OAuth2Credentials"
        credentials_expr = (
            "OAuth2Credentials(\n"
            '        access_token="fake-access-token",\n'
            "        refresh_token=None,\n"
            '        token_type="bearer",\n'
            "        expires_at=datetime.now(UTC) + timedelta(hours=1),\n"
            "        granted_scopes=(),\n"
            "    )"
        )
        # ruff's isort sorts "import x" statements before "from x import y" ones within a
        # group, regardless of module name — "import uuid" stays first.
        stdlib_imports.append("from datetime import UTC, datetime, timedelta")
    else:
        credentials_import = "from plugins._shared.credentials import ApiKeyCredentials"
        credentials_expr = 'ApiKeyCredentials(api_key="fake-key-for-tests")'
    stdlib_block = "\n".join(stdlib_imports)

    return f'''"""Runs the shared plugin contract test suite against this plugin — see
plugins/_shared/tests/test_plugin_contract.py and CONTRIBUTING.md "Adding a new plugin".
This only proves the plugin structurally honors its own manifest; add your own tests here
too for what each method actually does against the real external API (mocked or recorded,
not live network calls in the test suite)."""

from __future__ import annotations

{stdlib_block}

from plugins._shared.base import ResolvedConnection
{credentials_import}
from plugins._shared.tests.test_plugin_contract import assert_plugin_contract
from plugins.{name}.plugin import create_plugin

_FAKE_CONNECTION = ResolvedConnection(
    project_id=uuid.uuid4(),
    plugin_key="{name}",
    label="default",
    config={{}},
    credentials={credentials_expr},
)


def test_plugin_honors_its_manifest() -> None:
    assert_plugin_contract(create_plugin(connection=_FAKE_CONNECTION))
'''


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold a new GrowthOS plugin package.")
    parser.add_argument("name", help="Plugin key, e.g. 'reddit' — becomes plugins/<name>/")
    parser.add_argument(
        "--capabilities",
        default="searchable",
        help="Comma-separated capability list, e.g. searchable,publishable (default: searchable)",
    )
    parser.add_argument("--auth-type", default="api_key", choices=sorted(VALID_AUTH_TYPES))
    args = parser.parse_args()

    _validate_name(args.name)
    capabilities = [c.strip() for c in args.capabilities.split(",") if c.strip()]
    unknown = set(capabilities) - VALID_CAPABILITIES
    if unknown:
        raise SystemExit(
            f"Unknown capabilities: {sorted(unknown)}. Valid: {sorted(VALID_CAPABILITIES)}"
        )
    if not capabilities:
        raise SystemExit("At least one capability is required.")

    plugin_dir = REPO_ROOT / "plugins" / args.name
    if plugin_dir.exists():
        raise SystemExit(f"{plugin_dir} already exists — refusing to overwrite.")

    (plugin_dir / "tests").mkdir(parents=True)

    _write(plugin_dir / "__init__.py", "")
    _write(plugin_dir / "manifest.py", _manifest_py(args.name, capabilities, args.auth_type))
    _write(plugin_dir / "plugin.py", _plugin_py(args.name, capabilities))
    _write(plugin_dir / "pyproject.toml", _pyproject_toml(args.name))
    _write(plugin_dir / "README.md", _readme_md(args.name, capabilities, args.auth_type))
    _write(plugin_dir / "tests" / "__init__.py", "")
    _write(plugin_dir / "tests" / "test_contract.py", _test_contract_py(args.name, args.auth_type))

    print(f"Created plugins/{args.name}/\n")
    print("Next steps (see docs/plugins/QUICKSTART.md), all run from the repo root:")
    print(f"  1. Fill in plugins/{args.name}/manifest.py and plugins/{args.name}/plugin.py.")
    print(f"  2. uv pip install -e plugins/{args.name} --python backend/.venv")
    print(f"  3. backend/.venv/Scripts/python -m pytest plugins/{args.name}/tests -p no:cov")
    print(f"     backend/.venv/bin/python -m pytest plugins/{args.name}/tests -p no:cov")
    print("     (Windows first, macOS/Linux second)")


if __name__ == "__main__":
    main()
